### ISSUE TITLE
Enable OSI equivalent licenses (PR #58 pipeline fails)

### ISSUE THREAD

**Issue by AJRubio-Montero** [EOSC-synergy/sqaaas-reporting-plugins#59]
Good morning.

Yesterday I made the #58 pull request against the main branch in order to solve a bug. In the description of the pull request, the bug and the solution are described.

However, the pipeline fails in the  <QC.Ver> criterion.  

Am I doing the PR correctly?

Thank you very much.
Cheers.

**Comment by orviz** [comment]
@AJRubio-Montero your change is now in production instance, could you please check whether this issue is actually fixed? thanks!

**Comment by AJRubio-Montero** [comment]
Yes! This works fine.

The code is currently awarded with a Silver Badge at the QAaaS plaform :-)

Thank you very much Pablo,
I'm closing the issue.
